const { QueryInterface, Sequelize } = require("sequelize");
const bcrypt = require("bcrypt");
const User = require("../../models/User");

module.exports = {
  up: async (QueryInterface, Sequelize) => {
    const hashedPassword = await bcrypt.hash("123senha", 8);
    await User.bulkCreate([
      {
        name: "Elisa Luciana Adriana Assunção",
        email: "elisa.luciana.assuncao@almaquinas.com.br",
        password: hashedPassword,
        birth_date: "1957-07-16",
        user_type: "guia",
        sex: "F",
        cpf: 72208812158,
        cep: 58035125,
        address: "Rua Ticiano Cavalcanti",
        state: "PB",
        city: "João Pessoa",
      },
      {
        name: "Márcia Laís Analu Drumond",
        email: "brunokevinnunes@quarttus.com.br",
        password: hashedPassword,
        birth_date: "1964-07-04",
        user_type: "turista",
        sex: "F",
        cpf: 38145600006,
        cep: 59032140,
        address: "Travessa Mirabeau Pereira",
        state: "RN",
        city: "Natal",
      },
      {
        name: "Breno Diogo Silveira",
        email: "breno_silveira@muricy.com",
        password: hashedPassword,
        birth_date: "1988-03-15",
        user_type: "turista",
        sex: "M",
        cpf: 52264292075,
        cep: 27430230,
        address: "Avenida Georgeth Barbosa Leite",
        state: "RJ",
        city: "Quatis",
      },
      {
        name: "Marli Beatriz Carolina Ferreira",
        email: "marli_beatriz_ferreira@msds.com.br",
        password: hashedPassword,
        birth_date: "1981-03-15",
        user_type: "turista",
        sex: "F",
        cpf: 71165102307,
        cep: 58701420,
        address: "Travessa Mirabeau Pereira",
        state: "RN",
        city: "Natal",
      },
      {
        name: "Erick Theo Moreira",
        email: "erick.theo.moreira@saa.com.br",
        password: hashedPassword,
        birth_date: "1974-03-11",
        user_type: "guia",
        sex: "M",
        cpf: 92222646812,
        cep: 69047260,
        address: "Rua Professora Maria M. Fiuza",
        state: "AM",
        city: "Manaus",
      },
      {
        name: "Adriana Simone da Costa",
        email: "adriana_simone_dacosta@unitower.com.br",
        password: hashedPassword,
        birth_date: "1973-05-27",
        user_type: "turista",
        sex: "F",
        cpf: 88535294937,
        cep: 35501216,
        address: "Travessa Mirabeau Pereira",
        state: "RN",
        city: "Divinópolis",
      },
      {
        name: "Nicole Laís da Silva",
        email: "nicolelaisdasilva@moyageorges.com.br",
        password: hashedPassword,
        birth_date: "1957-04-03",
        user_type: "turista",
        sex: "F",
        cpf: 36322114344,
        cep: 76811518,
        address: "Rua Biribá",
        state: "RO",
        city: "Porto Velho",
      },
      {
        name: "Brenda Rosa da Conceição",
        email: "brenda-daconceicao98@agsolve.com.br",
        password: hashedPassword,
        birth_date: "1962-03-09",
        user_type: "turista",
        sex: "F",
        cpf: 43006398335,
        cep: 72880224,
        address: "Travessa Mirabeau Pereira",
        state: "RN",
        city: "Cidade Ocidental",
      },
      {
        name: "Giovanni Marcelo Nunes",
        email: "giovanni.marcelo.nunes@brasildakar.com.br",
        password: hashedPassword,
        birth_date: "1962-07-23",
        user_type: "guia",
        sex: "M",
        cpf: 67776851892,
        cep: 74393485,
        address: "Avenida Americano do Brasil",
        state: "GO",
        city: "Goiânia",
      },
      {
        name: "Samuel Lorenzo Oliveira",
        email: "samuel_oliveira@recoferindustria.com.br",
        password: hashedPassword,
        birth_date: "1948-08-04",
        user_type: "guia",
        sex: "M",
        cpf: 91589241916,
        cep: 85171180,
        address: "Avenida Manuel Pires do Prado",
        state: "SP",
        city: "São Paulo",
      },
      {
        name: "Carla Cristiane Teixeira",
        email: "carla_teixeira@abdalathomaz.adv.br",
        password: hashedPassword,
        birth_date: "1945-03-25",
        user_type: "turista",
        sex: "F",
        cpf: 77172033590,
        cep: 79073022,
        address: "Rua Rachid Abes",
        state: "MS",
        city: "Campo Grande",
      },
      {
        name: "Augusto Manoel Davi da Mota",
        email: "augusto_damota@ntiequipamentos.com.br",
        password: hashedPassword,
        birth_date: "1961-05-26",
        user_type: "guia",
        sex: "M",
        cpf: 70155756206,
        cep: 59114300,
        address: "Rua Maria José Lira",
        state: "RN",
        city: "Natal",
      },
      {
        name: "Lara Bianca Barros",
        email: "lara_barros@moncoes.com.br",
        password: hashedPassword,
        birth_date: "1978-04-",
        user_type: "turista",
        sex: "F",
        cpf: 22891583809,
        cep: 89370795,
        address: "Rua Afonso Tomaz",
        state: "SP",
        city: "Mauá",
      },
      {
        name: "Analu Marina Clarice Alves",
        email: "analu_marina_alves@atrix.com.br",
        password: hashedPassword,
        birth_date: "1977-07-21",
        user_type: "turista",
        sex: "F",
        cpf: 41006810030,
        cep: 87290970,
        address: "Avenida Liberdade 1842-B",
        state: "PR",
        city: "Luiziana",
      },
      {
        name: "Kauê Oliver Cauê Corte Real",
        email: "kaue.oliver.cortereal@trietto.com.br",
        password: hashedPassword,
        birth_date: "1957-03-18",
        user_type: "guia",
        sex: "M",
        cpf: 41679633295,
        cep: 55816470,
        address: "Rua Joaquim Gonçalves Guerra",
        state: "PE",
        city: "Carpina",
      },
      {
        name: "Aparecida Helena da Cruz",
        email: "aparecidahelenadacruz@sabesp.com.br",
        password: hashedPassword,
        birth_date: "1991-06-09",
        user_type: "turista",
        sex: "F",
        cpf: 58601473768,
        cep: 70650431,
        address: "Quadra SHCES Quadra 403 Bloco A",
        state: "DF",
        city: "Natal",
      },
      {
        name: "Marcelo Hugo Souza",
        email: "marcelohugosouza@tortasecreta.com",
        password: hashedPassword,
        birth_date: "1988-04-03",
        user_type: "turista",
        sex: "M",
        cpf: 78250494385,
        cep: 59032140,
        address: "Travessa Mirabeau Pereira",
        state: "RN",
        city: "Petrópolis",
      },
      {
        name: "Oliver Ryan Nascimento",
        email: "oliver.ryan.nascimento@hormail.com",
        password: hashedPassword,
        birth_date: "1992-04-02",
        user_type: "turista",
        sex: "M",
        cpf: 41969730862,
        cep: 60833073,
        address: "Travessa Expedito Leandro de Sousa",
        state: "CE",
        city: "Fortaleza",
      },
      {
        name: "Benício Paulo Jesus",
        email: "benicio.paulo.jesus@estruturalbr.com.br",
        password: hashedPassword,
        birth_date: "1948-06-10",
        user_type: "turista",
        sex: "M",
        cpf: 86794954761,
        cep: 69314224,
        address: "Rua Cruzeiro do sul",
        state: "RR",
        city: "Boa Vista",
      },
      {
        name: "Regina Cláudia Gomes",
        email: "reginaclaudiagomes@uel.br",
        password: hashedPassword,
        birth_date: "1955-04-21",
        user_type: "turista",
        sex: "F",
        cpf: 93650700310,
        cep: 63582974,
        address: "Rua do Comércio, s/n",
        state: "CE",
        city: "Baixio da Donana",
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await User.destroy({
      where: {
        email: [
          "11@email.com",
          "qqqq1111111@test.com",
          "d1111111111@test.com",
          "a8asld@test.com",
          "a8asld1111111111@test.com",
        ],
      },
    });
  },
};
