const { QueryInterface, Sequelize } = require("sequelize");
const Tour = require("../../models/Tour");

module.exports = {
  up: async (QueryInterface, Sequelize) => {
    await Tour.bulkCreate([
      {
        tour_title: "Praia de Copacabana",
        description:
          "Uma das praias mais famosas do mundo, localizada no Rio de Janeiro.",
        local: "Praia de Copacabana, Rio de Janeiro",
        price: 150.0,
        date: new Date(),
        max_number_users: 100,
        user_id: 1,
        cep: 22070011,
        address: "Avenida Atlântica",
        state: "Rio de Janeiro",
        city: "Rio de Janeiro",
        lat: -22.9711,
        lng: -43.1822,
      },
      {
        tour_title: "Cristo Redentor",
        description:
          "Uma das Novas Sete Maravilhas do Mundo, símbolo do Brasil.",
        local: "Corcovado, Rio de Janeiro",
        price: 120.0,
        date: new Date(),
        max_number_users: 50,
        user_id: 1,
        cep: 22271110,
        address: "Parque Nacional da Tijuca",
        state: "Rio de Janeiro",
        city: "Rio de Janeiro",
        lat: -22.9519,
        lng: -43.2105,
      },
      {
        tour_title: "Cataratas do Iguaçu",
        description:
          "Uma das maiores e mais impressionantes cachoeiras do mundo.",
        local: "Parque Nacional do Iguaçu, Paraná",
        price: 200.0,
        date: new Date(),
        max_number_users: 80,
        user_id: 9,
        cep: 85855750,
        address: "Rodovia BR 469",
        state: "Paraná",
        city: "Foz do Iguaçu",
        lat: -25.6953,
        lng: -54.4367,
      },
      {
        tour_title: "Floresta Amazônica",
        description: "Explore a maior floresta tropical do mundo.",
        local: "Manaus, Amazonas",
        price: 300.0,
        date: new Date(),
        max_number_users: 20,
        user_id: 15,
        cep: 69000000,
        address: "Avenida do Turismo",
        state: "Amazonas",
        city: "Manaus",
        lat: -3.119,
        lng: -60.0217,
      },
      {
        tour_title: "Pelourinho",
        description: "Bairro histórico e cultural em Salvador, Bahia.",
        local: "Salvador, Bahia",
        price: 100.0,
        date: new Date(),
        max_number_users: 30,
        user_id: 12,
        cep: 40026280,
        address: "Largo do Pelourinho",
        state: "Bahia",
        city: "Salvador",
        lat: -12.9714,
        lng: -38.5109,
      },
      {
        tour_title: "Chapada Diamantina",
        description:
          "Região montanhosa com paisagens naturais impressionantes.",
        local: "Lençóis, Bahia",
        price: 250.0,
        date: new Date(),
        max_number_users: 40,
        user_id: 5,
        cep: 46960000,
        address: "Parque Nacional da Chapada Diamantina",
        state: "Bahia",
        city: "Lençóis",
        lat: -12.5616,
        lng: -41.3925,
      },
      {
        tour_title: "Ilha Grande",
        description: "Ilha paradisíaca com praias e florestas tropicais.",
        local: "Angra dos Reis, Rio de Janeiro",
        price: 180.0,
        date: new Date(),
        max_number_users: 60,
        user_id: 1,
        cep: 23968970,
        address: "Vila do Abraão",
        state: "Rio de Janeiro",
        city: "Angra dos Reis",
        lat: -23.1547,
        lng: -44.1689,
      },
      {
        tour_title: "Parque Nacional dos Lençóis Maranhenses",
        description: "Conhecido por suas dunas de areia branca e lagoas azuis.",
        local: "Barreirinhas, Maranhão",
        price: 220.0,
        date: new Date(),
        max_number_users: 25,
        user_id: 9,
        cep: 65590000,
        address: "Parque Nacional dos Lençóis Maranhenses",
        state: "Maranhão",
        city: "Barreirinhas",
        lat: -2.6843,
        lng: -43.7026,
      },
      {
        tour_title: "Fernando de Noronha",
        description:
          "Arquipélago com algumas das praias mais bonitas do mundo.",
        local: "Fernando de Noronha, Pernambuco",
        price: 450.0,
        date: new Date(),
        max_number_users: 15,
        user_id: 9,
        cep: 53990000,
        address: "Ilha de Fernando de Noronha",
        state: "Pernambuco",
        city: "Fernando de Noronha",
        lat: -3.8576,
        lng: -32.4297,
      },
      {
        tour_title: "Pão de Açúcar",
        description: "Um dos cartões postais mais famosos do Rio de Janeiro.",
        local: "Urca, Rio de Janeiro",
        price: 110.0,
        date: new Date(),
        max_number_users: 70,
        user_id: 15,
        cep: 22290270,
        address: "Avenida Pasteur",
        state: "Rio de Janeiro",
        city: "Rio de Janeiro",
        lat: -22.9486,
        lng: -43.1566,
      },
      {
        tour_title: "Pantanal",
        description: "Maior planície alagada do mundo, rica em biodiversidade.",
        local: "Corumbá, Mato Grosso do Sul",
        price: 350.0,
        date: new Date(),
        max_number_users: 20,
        user_id: 1,
        cep: 79300000,
        address: "Pantanal",
        state: "Mato Grosso do Sul",
        city: "Corumbá",
        lat: -19.0148,
        lng: -57.6514,
      },
      {
        tour_title: "Ouro Preto",
        description: "Cidade histórica famosa por sua arquitetura colonial.",
        local: "Ouro Preto, Minas Gerais",
        price: 90.0,
        date: new Date(),
        max_number_users: 50,
        user_id: 5,
        cep: 35400000,
        address: "Centro Histórico",
        state: "Minas Gerais",
        city: "Ouro Preto",
        lat: -20.3859,
        lng: -43.5039,
      },
      {
        tour_title: "Bonito",
        description: "Destino de ecoturismo com rios cristalinos e cavernas.",
        local: "Bonito, Mato Grosso do Sul",
        price: 400.0,
        date: new Date(),
        max_number_users: 30,
        user_id: 10,
        cep: 79290000,
        address: "Centro",
        state: "Mato Grosso do Sul",
        city: "Bonito",
        lat: -21.1255,
        lng: -56.4804,
      },
      {
        tour_title: "Jalapão",
        description: "Região de cerrado com dunas, rios e cachoeiras.",
        local: "Mateiros, Tocantins",
        price: 300.0,
        date: new Date(),
        max_number_users: 20,
        user_id: 12,
        cep: 77593000,
        address: "Parque Estadual do Jalapão",
        state: "Tocantins",
        city: "Mateiros",
        lat: -10.54,
        lng: -46.634,
      },
      {
        tour_title: "Paraty",
        description: "Cidade colonial com praias e montanhas.",
        local: "Paraty, Rio de Janeiro",
        price: 160.0,
        date: new Date(),
        max_number_users: 40,
        user_id: 1,
        cep: 23970000,
        address: "Centro Histórico",
        state: "Rio de Janeiro",
        city: "Paraty",
        lat: -23.2221,
        lng: -44.7178,
      },
      {
        tour_title: "Porto de Galinhas",
        description: "Praia famosa por suas piscinas naturais.",
        local: "Ipojuca, Pernambuco",
        price: 140.0,
        date: new Date(),
        max_number_users: 60,
        user_id: 5,
        cep: 55590000,
        address: "Porto de Galinhas",
        state: "Pernambuco",
        city: "Ipojuca",
        lat: -8.5085,
        lng: -35.0032,
      },
      {
        tour_title: "Jericoacoara",
        description: "Vila de pescadores com praias paradisíacas.",
        local: "Jijoca de Jericoacoara, Ceará",
        price: 210.0,
        date: new Date(),
        max_number_users: 30,
        user_id: 9,
        cep: 62598000,
        address: "Praia de Jericoacoara",
        state: "Ceará",
        city: "Jijoca de Jericoacoara",
        lat: -2.7965,
        lng: -40.5124,
      },
      {
        tour_title: "Ilhabela",
        description: "Arquipélago com praias e trilhas na Mata Atlântica.",
        local: "Ilhabela, São Paulo",
        price: 170.0,
        date: new Date(),
        max_number_users: 50,
        user_id: 12,
        cep: 11630000,
        address: "Vila",
        state: "São Paulo",
        city: "Ilhabela",
        lat: -23.7785,
        lng: -45.3557,
      },
      {
        tour_title: "Chapada dos Veadeiros",
        description: "Parque nacional com cachoeiras e trilhas.",
        local: "Alto Paraíso de Goiás, Goiás",
        price: 230.0,
        date: new Date(),
        max_number_users: 25,
        user_id: 15,
        cep: 73770000,
        address: "Parque Nacional da Chapada dos Veadeiros",
        state: "Goiás",
        city: "Alto Paraíso de Goiás",
        lat: -14.1305,
        lng: -47.5272,
      },
      {
        tour_title: "Serra Gaúcha",
        description: "Região conhecida pelo turismo de inverno e vinícolas.",
        local: "Gramado, Rio Grande do Sul",
        price: 190.0,
        date: new Date(),
        max_number_users: 45,
        user_id: 10,
        cep: 95670000,
        address: "Centro",
        state: "Rio Grande do Sul",
        city: "Gramado",
        lat: -29.3734,
        lng: -50.8764,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await Tour.destroy({
      where: {
        id,
      },
    });
  },
};
